apiVersion: kaptain.org/1.11
kind: kubernetes-bundle-vendor-helm-rendered
metadata:
  description: "Vendored Envoy Gateway CRDs for cluster-wide installation"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
  main:
    vendorHelmRendered:
      ociChart: 'oci://docker.io/envoyproxy/gateway-helm'
      moveFiles:
        - source: 'crds/generated/gateway.envoyproxy.io_backends.yaml'
          destination: 'customresourcedefinition-backends.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml'
          destination: 'customresourcedefinition-backendtrafficpolicies.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml'
          destination: 'customresourcedefinition-clienttrafficpolicies.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml'
          destination: 'customresourcedefinition-envoyextensionpolicies.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml'
          destination: 'customresourcedefinition-envoypatchpolicies.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_envoyproxies.yaml'
          destination: 'customresourcedefinition-envoyproxies.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_httproutefilters.yaml'
          destination: 'customresourcedefinition-httproutefilters.yaml'
        - source: 'crds/generated/gateway.envoyproxy.io_securitypolicies.yaml'
          destination: 'customresourcedefinition-securitypolicies.yaml'
  global:
    release:
      versioning:
        maxParts: '4'
        strategy: file-pattern-match
        patternType: custom
        source:
          subPath: src/config
          fileName: VendorHelmRenderedVersion
          pattern: '^v?([0-9]+\.[0-9]+\.[0-9]+)$'
          prefixParts: '3'
